import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'ALIAS | Sovereign AI Admin & Business Intelligence Template',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return children;
}
