import type { Metadata } from 'next';

export const metadata: Metadata = {
	title: 'Fyr | React NextJs TypeScript Tailwind Admin & AI Chat Template',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return children;
}
